import React from "react";

import DefaultWrapper from "@/components/DefaultWrapper";
import { GitLink } from "@/components/Links";
import { TileTag } from "@/components/Tags";
import { Tile } from "@/components/Tiles";
import { PageInfo, TileInfo } from "@/components/Wrapper";
import { PageColor } from "@/lib/themes";
import { genPageTitle } from "@/lib/utils";

export default function Videntium() {
    let pageInfo = new PageInfo(
        genPageTitle(__filename),
        "Videntium",
        "Online map viewer for Imperium written in PHP",
        { backgroundColor: PageColor.SEGFAULT_MOSS },
        [TileTag.ACADEMIC, TileTag.PHP, TileTag.JS, TileTag.HTML],
        (
            <>
                <GitLink href={"https://github.com/matthew-pisano/Videntium"}>Videntium</GitLink>
            </>
        )
    );
    return (
        <DefaultWrapper pageInfo={pageInfo}>
            <Tile tileInfo={new TileInfo({ title: <h2>Overview</h2> })}>
                <p>
                    Videntium is an online map viewer for map files generated by <i>Imperium</i>. Users can upload any
                    Imperium map file to the website and view its various attributes. Users of the site can create an
                    account that is stored in a database, store uploaded maps to a separate database and choose to share
                    those maps publicly with all users.
                </p>
            </Tile>

            <Tile
                tileInfo={
                    new TileInfo({ title: <>Features and Function</>, thumbnail: "/media/image/videntiumMap.png" })
                }>
                <p>
                    Built using <i>AWS Cloud9</i>, Videntium is served to the user through PHP from AWS servers. The two
                    MySQL databases that Videntium uses as storage are created and managed by PHPMyAdmin for easier
                    management. The map viewer allows the user to toggle between different views of their map using
                    colored filters and text boxes to show information about the various provinces on the map.
                </p>
            </Tile>

            <Tile tileInfo={new TileInfo({ title: <>Implementation</> })}>
                <p>
                    The interpretation of uploaded maps is preformed on the front-end using code from Imperium that was
                    translated from Java to JavaScript. This allows the browser to preform the same viewing and
                    information interaction as within the same, although the process is considerably lighter without the
                    rest of the game's code running along side of it.
                </p>
            </Tile>

            <Tile tileInfo={new TileInfo({ title: <>Map Sharing</>, thumbnail: "/media/image/videntiumDB.png" })}>
                <p>
                    Users of Videntium are also able to make their maps public to all users of the website. On the page
                    that display's a user's private maps, all maps that are shared publicly are also shown. These maps
                    contain information such as the owner's name and the name of the map file. The user can then load
                    their personal maps or those publicly available into the viewer.
                </p>
            </Tile>
        </DefaultWrapper>
    );
}
