import React, { Component } from 'react';
import * as common from './common';
class Videntium extends Component {

    render() {
        let tiles = [
            {
                title: "#Overview",
                content: `Videntium is an online map viewer for map files generated by <i>Imperium</i>.  
                    Users can upload any Imperium map file to the website and view its various attributes.
                    Users of the site can create an account that is stored in a database, store uploaded maps
                    to a separate database and choose to share those maps publicly with all users.`
            },
            {
                title: "Features and Function",
                content: `Built using AWS Cloud9, Videntium is served to the user through PHP from AWS servers.
                    The two MySQL databases that Videntium uses as storage are created and managed by PHPMyAdmin for
                    easier management.  The map viewer allows the user to toggle between different views of their
                    map using colored filters and text boxes to show information about the various provinces on the map.`,
                thumbnail: "https://lightsail-image-repo.s3.amazonaws.com/pgrm/videntiumMap.png"
            },
            {
                title: "Implementation",
                content: `The interpretation of uploaded maps is preformed on the front-end using code from Imperium that
                    was translated from Java to JavaScript.  This allows the browser to preform the same viewing and
                    information interaction as within the same, although the process is considerably lighter without the
                    rest of the game's code running along side of it.`,
                thumbnail: ""
            },
            {
                title: "Map Sharing",
                content: `Users of Videntium are also able to make their maps public to all users of the website.
                    On the page that display's a user's private maps, all maps that are shared publicly are also shown.
                    These maps contain information such as the owner's name and the name of the map file.  The user can
                    then load their personal maps or those publicly available into the viewer.`,
                thumbnail: "https://lightsail-image-repo.s3.amazonaws.com/pgrm/videntiumDB.png"
            },
        ];
        let pageInfo = {
            holderStyle: {backgroundColor: "#876eba", borderRadius: "10px"},
            gitLink: "https://github.com/ReactorDevelopment/Videntium",
            gitTitle: "Videntium",
            tags: ["academic", "php", "js", "html"]
        };
        return (
            <div id="videntiumPage" className="page container w3-rest lightText" style={{display: "none"}}>
                <div className="inner titleCard" style={{position: "fixed", height: "300px", top: "50px", left: '0px', right: '0px'}}>
                    <h1 style={{margin: "auto", width: "auto", textAlign: "center"}}><b>Videntium</b></h1><br/>
                    <h3 style={{margin: "auto", width: "auto", textAlign: "center"}}>Online map viewer for Imperium written in PHP</h3>
                </div>
                {common.build(pageInfo, tiles)}
            </div>
        );
    }
}

export default Videntium;